// Code generated by MockGen. DO NOT EDIT.
// Source: doscg/pkg/doscg (interfaces: MessageService)

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "doscg/pkg/entity"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMessageService is a mock of MessageService interface
type MockMessageService struct {
	ctrl     *gomock.Controller
	recorder *MockMessageServiceMockRecorder
}

// MockMessageServiceMockRecorder is the mock recorder for MockMessageService
type MockMessageServiceMockRecorder struct {
	mock *MockMessageService
}

// NewMockMessageService creates a new mock instance
func NewMockMessageService(ctrl *gomock.Controller) *MockMessageService {
	mock := &MockMessageService{ctrl: ctrl}
	mock.recorder = &MockMessageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMessageService) EXPECT() *MockMessageServiceMockRecorder {
	return m.recorder
}

// NotifyBotError mocks base method
func (m *MockMessageService) NotifyBotError(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyBotError", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyBotError indicates an expected call of NotifyBotError
func (mr *MockMessageServiceMockRecorder) NotifyBotError(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyBotError", reflect.TypeOf((*MockMessageService)(nil).NotifyBotError), arg0)
}

// SendReply mocks base method
func (m *MockMessageService) SendReply(arg0 entity.BotMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendReply", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendReply indicates an expected call of SendReply
func (mr *MockMessageServiceMockRecorder) SendReply(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendReply", reflect.TypeOf((*MockMessageService)(nil).SendReply), arg0)
}
