// Code generated by MockGen. DO NOT EDIT.
// Source: doscg/pkg/doscg (interfaces: MapService)

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "doscg/pkg/entity"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMapService is a mock of MapService interface
type MockMapService struct {
	ctrl     *gomock.Controller
	recorder *MockMapServiceMockRecorder
}

// MockMapServiceMockRecorder is the mock recorder for MockMapService
type MockMapServiceMockRecorder struct {
	mock *MockMapService
}

// NewMockMapService creates a new mock instance
func NewMockMapService(ctrl *gomock.Controller) *MockMapService {
	mock := &MockMapService{ctrl: ctrl}
	mock.recorder = &MockMapServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMapService) EXPECT() *MockMapServiceMockRecorder {
	return m.recorder
}

// FindBestWayFromSCGToCentrallWorld mocks base method
func (m *MockMapService) FindBestWayFromSCGToCentrallWorld(arg0, arg1 string) (entity.BestRoute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBestWayFromSCGToCentrallWorld", arg0, arg1)
	ret0, _ := ret[0].(entity.BestRoute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBestWayFromSCGToCentrallWorld indicates an expected call of FindBestWayFromSCGToCentrallWorld
func (mr *MockMapServiceMockRecorder) FindBestWayFromSCGToCentrallWorld(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBestWayFromSCGToCentrallWorld", reflect.TypeOf((*MockMapService)(nil).FindBestWayFromSCGToCentrallWorld), arg0, arg1)
}
